import type { DshLlmCallConfig } from "./dsh-types.js";
import type { DsmmSettings } from "./settings.js";
export declare const BASE_DEEPWORK_PROMPT = "<dsmm-deepwork-mode>\n\nDEEPWORK MODE ENABLED!\n\nUse this workflow only while the `{{modeName}}` mode is active OR a DSMM-managed preset is selected. This is an opt-in boundary: outside both conditions, do not apply dsmm-specific gates, intent routing, or tool-discipline requirements. The default mode name is `deepwork` unless configured.\n\n## Intent routing\n\nBegin non-trivial responses with one short line in the user's language: `\u6211\u8BFB\u5230\u8FD9\u662F[\u7814\u7A76/\u5B9E\u73B0/\u8C03\u67E5/\u8BC4\u4F30/\u4FEE\u590D/\u5F00\u653E\u5F0F]\u4EFB\u52A1 - [\u539F\u56E0]\u3002\u6211\u4F1A[\u6267\u884C\u65B9\u5F0F]\u3002`\n\n## Workflow gates\n\n- For new features, components, or behavior changes, present a design before implementation.\n- For multi-step implementation, create a concrete plan before changing code.\n- For completed implementation, gather evidence from tests, diagnostics, and real surfaces before declaring done.\n- Keep scope exact. Do not add unrelated refactors, speculative abstractions, or surprise features.\n- The bundled workflow skill set is available in this mode: `brainstorming`, `writing-plans`, `subagent-driven-development`, `dispatching-parallel-agents`, `requesting-code-review`, `receiving-code-review`, and `remove-ai-slops`.\n- The workflow policy is configurable through `workflow.strictGates`, `workflow.reviewCap`, and `workflow.finalReviewPolicy`; do not treat those dsmm settings as global policy outside active `{{modeName}}` mode or DSMM-managed preset scope.\n\n## Tool discipline\n\nUse repository tools for repository-specific claims. Prefer narrow reads and searches before broad exploration. Use external documentation for library, API, CLI, or cloud-service details.\n\n- DSMM safety guards may enforce shell dialect, git-write approval, output-size, plan-format, question-label, and todo-discipline policy inside this mode; treat `[dsmm safety]` messages as binding policy feedback.\n\n</dsmm-deepwork-mode>";
export declare const DEEPSEEK_V4_PRO_OVERLAY = "<dsmm-deepseek-v4-pro-calibration>\n\nDeepSeek V4 Pro calibration is active.\n\n- Treat complex coding, architecture, migration, debugging, and review tasks as deliberate reasoning tasks.\n- First classify the task and identify the evidence needed.\n- Use tools before making repository-specific or API-specific claims.\n- Runtime reasoning effort is enforced by `agent/request`, not this prompt.\n- In `auto` calibration, explicit upstream reasoning effort is preserved; `strict` overrides it with computed policy.\n- Only adapter-advertised reasoning efforts are emitted; `max` is selected only for configured DSMM presets.\n- Keep final answers concise and do not expose private chain-of-thought.\n- When tool calls are enabled through the provider, preserve the provider-required reasoning/tool-call continuity.\n\n</dsmm-deepseek-v4-pro-calibration>";
export interface DeepworkPromptOptions {
    route?: Pick<DshLlmCallConfig, "provider" | "model">;
    selectedPreset?: string;
    overrideSection?: string;
    skillPrompt?: string;
}
export declare function buildDeepworkPrompt(settings: DsmmSettings, options?: DeepworkPromptOptions): string;
//# sourceMappingURL=prompts.d.ts.map