import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const home = process.env.DSH_HOME || mkdtempSync(join(tmpdir(), "dsmm-dsh-"));
const patch = join(root, "cordis.patch.yml");
const disabledRole = "dsmm-reviewer";

function requireSuccess(result, description) {
  if (result.error !== undefined) throw result.error;
  if (result.status !== 0) throw new Error(`${description} failed with status ${String(result.status)}`);
}

async function importDshAgentPresets() {
  const failures = [];

  try {
    return await import("@deepseek-ai/dsh-agent-presets");
  } catch (error) {
    failures.push(`direct import: ${error instanceof Error ? error.message : String(error)}`);
  }

  const npmRoot = spawnSync("npm", ["root", "-g"], { encoding: "utf8" });
  requireSuccess(npmRoot, "npm root -g");

  const globalRoot = npmRoot.stdout.trim();
  const requireFromHere = createRequire(import.meta.url);
  const searchPaths = [globalRoot, join(globalRoot, "@deepseek-ai", "dsh")];

  try {
    const resolved = requireFromHere.resolve("@deepseek-ai/dsh-agent-presets", { paths: searchPaths });
    return await import(pathToFileURL(resolved).href);
  } catch (error) {
    failures.push(`global resolver (${searchPaths.join(", ")}): ${error instanceof Error ? error.message : String(error)}`);
  }

  throw new Error(`could not import @deepseek-ai/dsh-agent-presets from installed dsh; ${failures.join("; ")}`);
}

function writeAgentPresetRootPatch(file, managedRoot) {
  writeFileSync(file, `# generated by dsmm Docker smoke; example profile patch, not dsmm default behavior
- id: agent-presets
  config:
    default: standard
    roots:
      - path: ${managedRoot}
        trust: user
    includeUserRoot: true
`, "utf8");
}

function assertContains(haystack, needle, description) {
  if (!haystack.includes(needle)) throw new Error(`${description} missing ${needle}`);
}

if (!existsSync(patch)) throw new Error(`missing ${patch}`);
if (!readFileSync(patch, "utf8").includes("id: dsmm")) throw new Error("cordis patch does not register dsmm");

if (process.env.DSMM_DOCKER_INNER !== "1") {
  const build = spawnSync("docker", [
    "build",
    "--build-arg",
    "DSH_PACKAGE=@deepseek-ai/dsh@latest",
    "-f",
    "docker/Dockerfile.smoke",
    "-t",
    "dsmm-dsh-smoke:0.1",
    ".."
  ], { cwd: root, stdio: "inherit" });
  requireSuccess(build, "docker build");

  const run = spawnSync("docker", ["run", "--rm", "dsmm-dsh-smoke:0.1"], { stdio: "inherit" });
  requireSuccess(run, "docker run");
  process.exit(0);
}

const install = spawnSync("dsh", ["plugin", "--profile", "dsmm-smoke", "add", root], {
  env: { ...process.env, DSH_HOME: home },
  stdio: "inherit"
});
requireSuccess(install, "dsh plugin add");

const dump = spawnSync("dsh", ["--profile", "dsmm-smoke", "--dump-config"], {
  env: { ...process.env, DSH_HOME: home },
  encoding: "utf8"
});
requireSuccess(dump, "dsh --dump-config");
if (!dump.stdout.includes("id: dsmm")) throw new Error("dumped dsh config did not include dsmm row");

const managedRoot = process.env.DSMM_MANAGED_PRESETS_ROOT || join(home, "managed-agent-presets-smoke");
const agentPresetRootPatch = join(home, "agent-presets-root.cordis.patch.yml");
const dsmm = await import(pathToFileURL(join(root, "lib", "index.js")).href);
const roles = Object.fromEntries(dsmm.DSMM_ROLE_IDS.map((id) => [id, id !== disabledRole]));

dsmm.materializeRolePresets({
  root: managedRoot,
  settings: {
    modeName: "deepwork",
    defaultActive: false,
    promptOrder: 50,
    deepseekV4ProCalibration: "auto",
    skills: {
      brainstorming: true,
      "writing-plans": true,
      "requesting-code-review": true,
      "receiving-code-review": true
    },
    roles,
    presets: {
      materialize: true,
      root: managedRoot
    }
  }
});

for (const id of dsmm.DSMM_ROLE_IDS) {
  const expected = join(managedRoot, id);

  if (id === disabledRole) {
    if (existsSync(expected)) throw new Error(`${disabledRole} should not be materialized`);
  } else if (!existsSync(join(expected, "agent.cordis.yml"))) {
    throw new Error(`${id} was not materialized into the managed root`);
  }
}

writeAgentPresetRootPatch(agentPresetRootPatch, managedRoot);

const dumpWithPresetRoot = spawnSync("dsh", ["--profile", "web", "--patch", agentPresetRootPatch, "--dump-config"], {
  env: { ...process.env, DSH_HOME: home },
  encoding: "utf8"
});
requireSuccess(dumpWithPresetRoot, "dsh --dump-config with agent-presets root patch");
assertContains(dumpWithPresetRoot.stdout, managedRoot, "dumped dsh config");
assertContains(dumpWithPresetRoot.stdout, "default: standard", "dumped dsh config");
if (/default:\s+dsmm-/u.test(dumpWithPresetRoot.stdout)) throw new Error("dsmm must not become the default dsh preset");

const agentPresets = await importDshAgentPresets();
if (typeof agentPresets.discoverPresets !== "function") {
  throw new Error("@deepseek-ai/dsh-agent-presets did not export discoverPresets()");
}

const discovered = await agentPresets.discoverPresets([{ path: managedRoot, trust: "user" }]);
const discoveredIds = discovered.map((preset) => preset.id);

for (const id of dsmm.DSMM_ROLE_IDS) {
  if (id === disabledRole) {
    if (discoveredIds.includes(id)) throw new Error(`${disabledRole} should be absent from dsh preset discovery`);
  } else if (!discoveredIds.includes(id)) {
    throw new Error(`${id} was not discovered by dsh discoverPresets()`);
  }
}
